routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return redirect()->route('login');
	// return view('dashboard');
});

Route::get('/transaksi', 'AkadController@transaksi');

Route::middleware('auth')->group(function () {
	Route::group(['prefix' => 'akad'], function () {
		Route::get('/', 'AkadController@index')->name('akad.index');
		Route::get('/create', 'AkadController@create')->name('akad.create');
		Route::get('/edit/{id}', 'AkadController@edit')->name('akad.edit');

		Route::get('/nasabah-akad', 'AkadController@nasabah_akad')->name('akad.nasabah-akad');
		Route::get('/akad-jatuh-tempo', 'AkadController@akad_jatuh_tempo')->name('akad.akad-jatuh-tempo');
		Route::get('/pelunasan-lelang', 'AkadController@pelunasan_lelang')->name('akad.pelunasan-lelang');
		Route::get('/lokasi-distribusi', 'AkadController@lokasi_distribusi')->name('akad.lokasi-distribusi');
		Route::get('/maintenance', 'AkadController@maintenance')->name('akad.maintenance');
		Route::get('/ringkasan-harian', 'AkadController@ringkasan_harian')->name('akad.ringkasan-harian');

		Route::get('/change-checklist/{id}', 'AkadController@change_checklist')->name('akad.change-checklist');
		Route::get('/change-location/{id}/{type}', 'AkadController@change_location')->name('akad.change-location');

		Route::group(['prefix' => 'ajax'], function(){
			Route::get('/fetch-data', 'AkadController@fetch_data')->name('akad.fetch-data');
			Route::get('/bayar-akad', 'AkadController@bayar_akad')->name('akad.bayar-akad');
			Route::get('/fetch-data-biaya-titip', 'AkadController@fetch_data_biaya_titip')->name('akad.fetch-data-biaya-titip');

			Route::get('/insert-data', 'AkadController@insert_data')->name('akad.insert-data');
			
			Route::post('/bayar-akad-ulang', 'AkadController@bayar_akad_ulang')->name('akad.bayar-akad-ulang');
		});

		Route::post('/store', 'AkadController@store')->name('akad.store');
		Route::post('/update/{id}', 'AkadController@update')->name('akad.update');
	});
	Route::group(['prefix' => 'cabang'], function () {
		Route::get('/', 'CabangController@index')->name('cabang.index');
		Route::get('/edit', 'CabangController@edit')->name('cabang.edit');
		Route::get('/create', 'CabangController@create')->name('cabang.create');

		Route::post('/store', 'CabangController@store')->name('cabang.store');
		Route::post('/update/{id}', 'CabangController@update')->name('cabang.update');
	});
	Route::group(['prefix' => 'cetak'], function(){
		Route::get('/pdf', 'CetakController@pdf')->name('pdf');
		Route::get('/print', 'CetakController@print')->name('print');
	});
	Route::group(['prefix' => 'nasabah'], function () {
		Route::get('/', 'NasabahController@index')->name('nasabah.index');
		Route::get('/ajax', 'NasabahController@ajax')->name('nasabah.ajax');
		Route::get('/edit/{id}', 'NasabahController@edit')->name('nasabah.edit');
		Route::get('/detail/{id}', 'NasabahController@detail')->name('nasabah.detail');

		Route::post('/update/{id}', 'NasabahController@update')->name('nasabah.update');
	});
	Route::group(['prefix' => 'operasional'], function () {
		Route::get('/create', 'OperasionalController@create')->name('operasional.create');
		Route::get('/bku-admin', 'OperasionalController@bku')->name('operasional.bku');
		Route::get('/data-pengeluaran', 'OperasionalController@pengeluaran')->name('operasional.pengeluaran');
		Route::get('/change-status/{id}', 'OperasionalController@change_status')->name('operasional.change-status');
		Route::get('/hutang-dan-pembayaran', 'OperasionalController@hutang')->name('operasional.hutang');

		Route::post('/store', 'OperasionalController@store')->name('operasional.store');
		Route::post('/hutang/store', 'OperasionalController@hutang_store')->name('operasional.hutang.store');
	});
	Route::group(['prefix' => 'pembayaran'], function () {
		Route::get('/bku', 'PembayaranController@bku')->name('pembayaran.bku');
		Route::get('/pendapatan', 'PembayaranController@pendapatan')->name('pembayaran.pendapatan');

		Route::get('/cair-pendapatan', 'PembayaranController@cair_pendapatan')->name('pembayaran.cair-pendapatan');
		Route::get('/reset-pendapatan', 'PembayaranController@reset_pendapatan')->name('pembayaran.reset-pendapatan');

		Route::get('/fetch-biaya-titip', 'PembayaranController@fetch_biaya_titip');
	});
	Route::group(['prefix' => 'permodalan'], function () {
		// url create for 'tambah saldo' & 'refund saldo'
		Route::get('/penambahan-saldo', 'PermodalanController@penambahan')->name('permodalan.penambahan');
		Route::get('/hutang-dan-piutang', 'PermodalanController@hutang')->name('permodalan.hutang');
		Route::get('/create/tambah-saldo', 'PermodalanController@create')->name('permodalan.create.tambah-saldo');
		Route::get('/create/refund-saldo', 'PermodalanController@create')->name('permodalan.create.refund-saldo');
		Route::get('/list-data-refund-saldo', 'PermodalanController@list_refund')->name('permodalan.list.refund');
		Route::get('/change-status/{id}/{code}', 'PermodalanController@change_status')->name('permodalan.change_status');

		Route::post('/store', 'PermodalanController@store')->name('permodalan.store');
	});
	Route::group(['prefix' => 'setting'], function () {
		Route::get('/', 'SettingController@index')->name('setting.index');
		Route::get('/store', 'SettingController@store')->name('setting.store');
		Route::get('/cabang', 'SettingController@pilih_cabang')->name('setting.pilih-cabang');
		Route::get('/data-login', 'SettingController@login')->name('setting.login');
		Route::get('/update/{id}', 'SettingController@update')->name('setting.update');
		Route::get('/delete/{id}', 'SettingController@delete')->name('setting.delete');
		Route::get('/validate-data', 'SettingController@validate_data')->name('setting.validate_data');
		
		Route::post('/cabang/store', 'SettingController@pilih_cabang_store')->name('setting.pilih-cabang.store');
	});
	Route::group(['prefix' => 'user'], function () {
		Route::get('/', 'UserController@index')->name('user.index');
		Route::get('/create', 'UserController@create')->name('user.create');
		Route::get('/edit/{id}', 'UserController@edit')->name('user.edit');

		Route::post('/store', 'UserController@store')->name('user.store');
		Route::post('/update/{id}', 'UserController@update')->name('user.update');
		Route::get('/destroy/{id}', 'UserController@destroy')->name('user.destroy');
	});
});

Route::get('/api', 'CabangController@api');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::namespace('auth')->group(function () {
	Route::get('/refresh-captcha', 'LoginController@refresh_captcha');
});

app/Models/Atk.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Atk extends Model
{
    protected $table        = "atk";
    public $timestamps      = false;
    protected $primaryKey   = 'id_atk';
    // protected $guarded   = [];
    protected $fillable     = [
    	'id_atk',
        'id_cabang',
    	'tanggal_atk',
    	'jumlah_atk',
    	'keterangan',
    ];

    // how to fetch data by username of user
    public function scopeIdCabang($query)
    {
        // get data id_cabang from table 'user_cabang' base on this user
        $user_cabang    = User_cabang::baseUsername()->first();

        return $query->where('id_cabang', $user_cabang->id_cabang);
    }

    public function scopeSearch($query, $by, $q)
    {
        return $query->where($by, 'LIKE', '%'.$q.'%');
    }

    public function scopeSorted($query, $by = 'tanggal_atk', $sort = 'desc')
    {
        return $query->orderBy($by, $sort);
    }

    public function getNominalJumlahAttribute()
    {
        return nominal($this->jumlah_atk);
    }
}

app/Models/Bku.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

use App\Models\Cabang;
use App\Models\User_cabang;

class Bku extends Model
{
    protected $table        = "bku";
    public $timestamps      = false;
    protected $primaryKey   = 'id_bku';
    // protected $guarded   = [];
    protected $fillable     = [
    	'id_bku',
        'jenis',
        'tanggal',
        'uraian',
        'debit',
        'kredit',
        'saldo',
        'id_cabang',
    ];

    // how to fetch data by username of user
    public function scopeBaseBranch($query)
    {
        // get data id_cabang from table 'user_cabang' base on this user
        $user_cabang    = User_cabang::baseUsername()->first();

    	return $query->where('id_cabang', $user_cabang->id_cabang);
    }

    public function scopeSearch($query, $by, $key)
    {
        return $query->where($by, 'LIKE', '%'.$key.'%');
    }

    public function scopeSorted($query, $by = 'tanggal', $sort = 'desc')
    {
        return $query->orderBy($by, $sort);
    }

    public function scopeJenis($query, $type)
    {
        return $query->where('jenis', $type);
    }

    public function getNominalDebitAttribute()
    {
        return nominal(floatval($this->debit));
    }

    public function getNominalKreditAttribute()
    {
        return nominal(floatval($this->kredit));
    }

    public function getNominalSaldoAttribute()
    {
        return nominal(floatval($this->saldo));
    }
}

app/Models/Saldo_cabang.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

use App\Models\User_cabang;

class Saldo_cabang extends Model
{
    protected $table        = "saldo_cabang";
    public $timestamps      = false;
    protected $primaryKey   = 'id_saldo_cabang';
    // protected $guarded   = [];
    protected $fillable     = [
    	'id_saldo_cabang',
        'id_cabang',
        'total_saldo',
    ];

   // how to fetch data by username of user
    public function scopeBaseBranch($query)
    {
        // get data id_cabang from table 'user_cabang' base on this user
        $user_cabang    = User_cabang::baseUsername()->first();

        return $query->where('id_cabang', $user_cabang->id_cabang);
    }

    public function getNominalTotalSaldoAttribute()
    {
        return nominal($this->total_saldo);
    }
}

app/Http/Controllers/OperasionalController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Atk;
use App\Models\Bku;
use App\Models\Hutang_kas;
use App\Models\Saldo_cabang;

use Auth;
use Carbon\Carbon;

class OperasionalController extends Controller
{
    public function __construct(
                                Atk $atk,
                                Bku $bku,
                                Request $request,
                                Hutang_kas $hutang_kas,
                                Saldo_cabang $saldo_cabang
                            )
    {
        $this->atk          = $atk;
        $this->bku          = $bku;
        $this->request      = $request;
        $this->hutang_kas   = $hutang_kas;
        $this->saldo_cabang = $saldo_cabang;

        view()->share([
            'menu'          => 'operasional',
            'subMenu'       => '',
            'menuHeader'    => config('library.menu_header'),
        ]);
    }

    public function create()
    {
    	return $this->template('operasional.form', array());
    }

    public function store()
    {
        $input = $this->request->except('_token');
        // return $input;

        $atk = $this->atk;
        $atk->id_cabang     = $this->id_cabang();
        $atk->keterangan    = request('keterangan');
        $atk->jumlah_atk    = remove_dot(request('jumlah'));
        $atk->tanggal_atk   = Carbon::now()->format('Y-m-d');
        $atk->save();

        $message = '<strong>Sukses!</strong> Data Atk berhasil di tambah';
        flash_message('message', $message);

        return redirect()->route('operasional.create');
    }

    public function bku()
    {
        $bku = $this->bku->idCabang()->sorted();

        if(request('by')){
            $bku = $bku->search(request('by'), request('q'));
        }

        $bku = $bku->paginate(request('perpage', 10));

    	$column = config('library.column.bku');

        return $this->template('operasional.bku', compact('column', 'bku'));
    }

    public function pengeluaran()
    {
        $atk = $this->atk->sorted();

        if(request('by')){
            $atk = $atk->search(request('by'), request('q'));
        }

        $atk     = $atk->paginate(request('perpage', 10));

        $column = config('library.column.pengeluaran');

    	return $this->template('operasional.pengeluaran', compact('column', 'atk'));
    }

    public function hutang()
    {
        $hutang_kas = $this->hutang_kas->sorted();

        if(request('by')){
            $hutang_kas = $hutang_kas->search(request('by'), request('q'));
        }

        $hutang_kas     = $hutang_kas->paginate(request('perpage', 10));

        $column = config('library.column.hutang');

        $saldo_cabang = $this->saldo_cabang->baseBranch()->first();

        return $this->template('operasional.hutang', compact('column', 'hutang_kas', 'saldo_cabang'));
    }

    public function hutang_store()
    {
        $input = $this->request->except('_token');
        // return $input;

        $hutang_kas                = $this->hutang_kas;
        $hutang_kas->id_cabang     = request('id_cabang');
        $hutang_kas->jumlah        = remove_dot(request('jumlah'));
        $hutang_kas->uraian        = request('keterangan');
        $hutang_kas->tanggal_hutang= Carbon::now()->format('Y-m-d');
        $hutang_kas->status_hutang = 'Belum Lunas';
        $hutang_kas->save();

        $message    = '<strong>Sukses!</strong> Data Hutang Cabang telah di tambah';
        flash_message('message', $message);

        return redirect()->route('operasional.hutang');
    }

    public function change_status($id)
    {
        $hutang_kas = $this->hutang_kas->find($id);
        $hutang_kas->status_hutang = "Lunas";
        $hutang_kas->save();

        $message    = '<strong>Sukses!</strong> Data Hutang Cabang telah di perbaharui';
        flash_message('message', $message);

        return redirect()->route('operasional.hutang');
    }
}

resources/views/operasional/bku.blade.php
@extends('_layouts.default')

@section('script-bottom')
    <script>

    </script>
@endsection

@section('content')
<div class="page-header">
    <div class="row">
        <div class="col-md-8">
            <div class="page-header-title">
                <div class="d-inline">
                    <h4>BKU Kas</h4>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            {{-- <div class="page-header-breadcrumb">
                <ul class="breadcrumb-title">
                    <li class="breadcrumb-item">
                        <a href="index.html"> <i class="feather icon-home"></i> </a>
                    </li>
                    <li class="breadcrumb-item"><a href="#!">Form Picker</a></li>
                </ul>
            </div> --}}
        </div>
    </div>
</div>
<div class="page-body">
    <div class="row">
        <div class="col-sm-12 col-md-12">
             {!! session()->get('message') !!}
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12 col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="sub-title">List Data</div>
                </div>
                <form method="get">
                <div class="card-block">
                     <!-- Row start -->
                     <div class="row">
                        <div class="col-sm-12 col-md-2">
                             <div class="form-group">
                                {{-- Show &nbsp; --}}
                                <select name="perpage" id="perpage" class="form-control">
                                    <option {{ selected(10, 'perpage', 'request')}}>10</option>
                                    <option {{ selected(25, 'perpage', 'request')}}>25</option>
                                    <option {{ selected(50, 'perpage', 'request')}}>50</option>
                                    <option {{ selected(100, 'perpage', 'request')}}>100</option>
                                </select> 
                                {{-- &nbsp; Entries --}}
                            </div>
                        </div>
                        <div class="col-sm-12 col-md-6 offset-md-4">
                            <div class="row">
                                <div class="col-sm-12 col-md-3 offset-md-1">
                                    <div class="form-group">
                                        <select name="by" id="by" class="form-control">
                                            @foreach($column as $index => $item)
                                                <option value="{{$index}}" {{selected($index, 'by', 'request')}}>{{$item}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="col-sm-12 col-md-5">
                                    <div class="input-group input-group-success">
                                        <span class="input-group-addon">
                                           <i class="icofont icofont-ui-search"></i>
                                        </span>
                                        <input type="text" name="q" id="q" value="{{ request('q') }}" class="form-control" placeholder="Search">
                                    </div>
                                </div>
                                <div class="col-sm-2 col-md-2">
                                    <button type="submit" class="btn btn-default" id="btn-search">Oke</button>
                                </div>
                            </div>
                        </div>
                    </div><br>
                    </form>
                    <div class="table-responsive dt-responsive">
                        <table id="dt-ajax-array" class="table table-striped table-bordered nowrap">
                            <thead>
                            <tr>
                                <th>No</th>
                                @foreach($column as $index => $item)
                                    <th>{{$item}}</th>
                                @endforeach
                            </tr>
                            </thead>
                            <tbody>
                                @forelse($bku as $index => $item)
                                    <tr>
                                        <td>{{$index + 1}}</td>
                                        <td>{{$item->tanggal}}</td>
                                        <td>{{$item->uraian}}</td>
                                        <td>Rp. {{$item->nominal_debit}}</td>
                                        <td>Rp. {{$item->nominal_kredit}}</td>
                                        <td>Rp. {{$item->nominal_saldo}}</td>
                                    </tr>
                                @empty
                                <tr>
                                    <td colspan="11" align="center">No data available in table</td>
                                </tr>
                                @endforelse
                            </tbody>
                            {{-- <tfoot>
                            </tfoot> --}}
                        </table>
                    </div>
                   {!! $bku->appends(Request::input())->render('vendor.pagination.bootstrap-4'); !!}                   
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/operasional/hutang.blade.php
@extends('_layouts.default')

@section('script-bottom')
    <script src="{{asset('adminty/files/assets/pages/form-masking/inputmask.js')}}"></script>
    <script src="{{asset('adminty/files/assets/pages/form-masking/jquery.inputmask.js')}}"></script>
    <script src="{{asset('adminty/files/assets/pages/form-masking/autoNumeric.js')}}"></script>
    <script src="{{asset('adminty/files/assets/pages/form-masking/form-mask.js')}}"></script>
    <script>
        function edit(url)
        {
            bootbox.confirm({
                message: 'Anda yakin data ini status menjadi LUNAS ?',
                buttons: {
                    confirm: {
                        label: 'OK',
                        className: 'btn-success ml-1'
                    },
                    cancel: {
                        label: 'Cancel',
                        className: 'btn-danger'
                    }
                },
                callback: function(result){
                    if(result == true){
                        // console.log(url)
                        window.location.href = url
                    }
                }
            });
        }

        function create(){
            $('#modal-add').modal('show')
        }
    </script>
@endsection

@section('content')
@include('operasional.modal')
<div class="page-header">
    <div class="row">
        <div class="col-md-8">
            <div class="page-header-title">
                <div class="d-inline">
                    <h4>Hutang Kas</h4>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            {{-- <div class="page-header-breadcrumb">
                <ul class="breadcrumb-title">
                    <li class="breadcrumb-item">
                        <a href="index.html"> <i class="feather icon-home"></i> </a>
                    </li>
                    <li class="breadcrumb-item"><a href="#!">Form Picker</a></li>
                </ul>
            </div> --}}
        </div>
    </div>
</div>
<div class="page-body">
    <div class="row">
        <div class="col-sm-12 col-md-12">
             {!! session()->get('message') !!}
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12 col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="sub-title">Data Hutang</div>
                </div>
                <form method="get">
                <div class="card-block">
                    <div class="row">
                        <div class="col-sm-12 col-md-6">
                            <a href="javascript:void(0)" onClick="create()" class="btn btn-success">Buat</a>
                        </div>
                    </div>
                    <br>
                     <!-- Row start -->
                     <div class="row">
                        <div class="col-sm-12 col-md-2">
                             <div class="form-group">
                                {{-- Show &nbsp; --}}
                                <select name="perpage" id="perpage" class="form-control">
                                    <option {{ selected(10, 'perpage', 'request')}}>10</option>
                                    <option {{ selected(25, 'perpage', 'request')}}>25</option>
                                    <option {{ selected(50, 'perpage', 'request')}}>50</option>
                                    <option {{ selected(100, 'perpage', 'request')}}>100</option>
                                </select>
                                {{-- &nbsp; Entries --}}
                            </div>
                        </div>
                        <div class="col-sm-12 col-md-6 offset-md-4">
                            <div class="row">
                                <div class="col-sm-12 col-md-3 offset-md-1">
                                    <div class="form-group">
                                        <select name="by" id="by" class="form-control">
                                            @foreach($column as $index => $item)
                                                <option value="{{$index}}" {{selected($index, 'by', 'request')}}>{{$item}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="col-sm-12 col-md-5">
                                    <div class="input-group input-group-success">
                                        <span class="input-group-addon">
                                           <i class="icofont icofont-ui-search"></i>
                                        </span>
                                        <input type="text" name="q" id="q" value="{{ request('q') }}" class="form-control" placeholder="Search">
                                    </div>
                                </div>
                                <div class="col-sm-2 col-md-2">
                                    <button type="submit" class="btn btn-default" id="btn-search">Oke</button>
                                </div>
                            </div>
                        </div>
                    </div><br>
                    </form>
                    <div class="table-responsive dt-responsive">
                        <table id="dt-ajax-array" class="table table-striped table-bordered nowrap">
                            <thead>
                            <tr>
                                <th>No</th>
                                @foreach($column as $index => $item)
                                    <th>{{$item}}</th>
                                @endforeach
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                                @forelse($hutang_kas as $index => $item)
                                    <tr>
                                        <td>{{$index + 1}}</td>
                                        <td>Rp. {{$item->nominal_jumlah}}</td>
                                        <td>{{$item->uraian}}</td>
                                        <td>{{$item->tanggal_hutang}}</td>
                                        <td>{{$item->status_hutang}}</td>
                                        <td>
                                        <a href="javascript:void(0)" class="btn btn-sm btn-primary" onClick="edit('{{url('operasional/change-status', $item->id_hutang_kas)}}')" title="Edit Data" id="detail_{{ $item->id_hutang_kas }}">
                                                <i class="icofont icofont-edit icofont-lg"></i>
                                            </a>
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="11" align="center">No data available in table</td>
                                    </tr>
                                @endforelse
                            </tbody>
                            {{-- <tfoot>
                            </tfoot> --}}
                        </table>
                    </div>
                   {!! $hutang_kas->appends(Request::input())->render('vendor.pagination.bootstrap-4'); !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/operasional/modal.blade.php
<div class="modal fade" id="modal-add"  tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Hutang Kas</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{{route('operasional.hutang.store')}}" method="post">
			    <input type="hidden" name="_method" value="post">
			    {{csrf_field()}}
			    <div class="row">
			        <div class="col-sm-12">
			            {{-- <h3 class="sub-title">Form Belanja ATK</h3> --}}
			             <div class="form-group row">
	                        <label class="col-sm-2 col-form-label" for="jumlah">Saldo Cabang</label>
	                        <div class="col-sm-10">
	                           <input value="{{$saldo_cabang->nominal_total_saldo}}" type="text" class="form-control" name="jumlah" id="jumlah" disabled>
	                           <input type="hidden" name="id_cabang" value="{{$saldo_cabang->id_cabang}}">
	                        </div>
	                    </div>
	                    <div class="form-group row">
	                        <label class="col-sm-2 col-form-label">Jumlah</label>
	                        <div class="col-sm-8 col-lg-10">
	                            <div class="input-group">
	                                <span class="input-group-addon" id="basic-addon1">Rp</span>
	                                <input type="text" class="form-control autonumber" data-v-min="0" data-v-max="9999999999" data-a-sep="." data-a-dec="," name="jumlah" id="jumlah" placeholder="Jumlah" required>
	                            </div>
	                        </div>
	                    </div>
	                    <div class="form-group row">
	                        <label class="col-sm-2 col-form-label" for="keterangan">Keterangan</label>
	                        <div class="col-sm-10">
	                           <textarea rows="5" cols="5" class="form-control" id="keterangan" name="keterangan" placeholder="Keterangan" required></textarea>
	                        </div>
	                    </div>
			        </div>
			    </div>
			    <button type="submit" class="btn btn-primary btn-xs ">Proses</button>
				</form>
            </div>
            {{-- <div class="modal-footer">
                <button type="button" class="btn btn-default btn-success waves-effect" >Proses</button>
            </div> --}}
        </div>
    </div>
</div>